## Useful macros ##
FUNCTION (INSTALL_PLUGIN name)

	IF (INSTALL_ON_POSTBUILD)
		ADD_CUSTOM_COMMAND( TARGET ${name} POST_BUILD
			COMMAND ${CMAKE_COMMAND} -E copy "${LIBRARY_OUTPUT_PATH}/${name}.dll"
											  ${VRED_PLUGIN_DIR}/${name}.dll
		)
	ENDIF ()
	
	IF (VISLAB_PACKAGING)
		INSTALL (TARGETS ${name} DESTINATION .)
	ENDIF ()
	
	# TODO INSTALL
	
ENDFUNCTION()